name: prompter_nvr
version: 0.0.3
description: Library to create CLI wizards. it is used to create both multiple-choice and binary questions on terminal.
homepage: https://github.com/nvrr/prompter_library.git

environment:
  sdk: '<3.0.0'